# Generated by Django 2.2.5 on 2023-02-24 03:12

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_name', models.CharField(default='Artist', max_length=250)),
                ('venue', models.CharField(default='Venue', max_length=250)),
                ('concertDate', models.DateField(default=datetime.date.today)),
            ],
            managers=[
                ('concerts', django.db.models.manager.Manager()),
            ],
        ),
    ]
