# Generated by Django 2.2.5 on 2023-02-24 04:27

import ConcertTracker.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConcertTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concertDate',
            field=models.DateField(default=datetime.date.today, validators=[ConcertTracker.models.present_or_future_date]),
        ),
    ]
